name: "KiBot action using quick-start"

# Controls when the action will run. Triggers the workflow on push or manual event
on:
  - push
  - workflow_dispatch

jobs:
  quick:
    name: "Quick Start (action)"
    runs-on: ubuntu-latest

    steps:
    - name: Get repo
      uses: actions/checkout@v4
      with:
        # So we can run a diff between last 2 changes
        fetch-depth: '0'

    - name: Run KiBot
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        quickstart: YES

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: Automatic_outputs
        path: Generated
